title:
  en: Abstracts
  uk: Конспекти
email: sakhnik@gmail.com
description:
  en: Random discoveries around programming, software development and life.
  uk: Різні відкриття у програмуванні, розробці програмного забезпечення і житті.
index:
  en: index.html
  uk: index.uk.html
feed:
  en: /feed.xml
  uk: /feed.uk.xml
suffix:
  en: .html
  uk: .uk.html

switch_lang:
  en: uk
  uk: en

i18n:
  langname:
    en: English
    uk: Українська
  langicon:
    en: /assets/united-kingdom-flag-icon-32.png
    uk: /assets/ukraine-flag-icon-32.png
  posts:
    en: Posts
    uk: Публікації
  subscribe:
    en: subscribe
    uk: підписатися
  via:
    en: via
    uk: через
  more:
    en: read more
    uk: читати далі

custom_paginate: 10

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakhnik.com"
twitter_username: sakhnik
github_username:  sakhnik

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-86803861-1

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
