title:
  en: Abstracts
  uk: Конспекти
email: sakhnik@gmail.com
description:
  en: Random discoveries around programming, software development and life.
  uk: Різні відкриття у програмуванні, розробці програмного забезпечення і житті.
index:
  en: index.html
  uk: index.uk.html
feed:
  en: /feed.xml
  uk: /feed.uk.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakhnik.com"
twitter_username: sakhnik
github_username:  sakhnik

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-86803861-1

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
