title: Abstracts
email: sakhnik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random discoveries around programming, software development
  and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sakhnik.com.ua"
twitter_username: sakhnik
github_username:  sakhnik

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-86803861-1

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
